# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

schedules:
- cron: "10 21 * * *"
  displayName: "Daily Automatic Pipeline Run"
  branches:
    include:
      - main
  always: true    

pool:
  vmImage: ubuntu-latest #windows-latest #macos-latest

parameters:
  - name: SCRIPT_KEY_VAL2
    displayName: 'Select Script Key' 
    type: string
    default: 'test_demo_ui_cr_hl_api_novisual'
    values:
      - 'test_demo_ui_cr_hl_api_novisual'
      - 'test_demo'
      - 'test_demo_api'
      - 'test_demo_ui_cr_hd_api'

steps:
- task: UseNode@1
  inputs:
    version: '22.x'

- script: npm ci 
  displayName: 'Install Playwrite Dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

#- script: SECRET_KEY=$(SECRET_KEY_VAL) npm run $(SCRIPT_KEY_VAL)
- script: SECRET_KEY=$(SECRET_KEY_VAL) npm run ${{parameters.SCRIPT_KEY_VAL2}}
  displayName: 'Run Tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  condition: always()  


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**test-results/junit-report.xml'
    testRunTitle: 'Playwright Junit Report'
  condition: always()  







