# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest #windows-latest #macos-latest

steps:
- task: UseNode@1
  inputs:
    version: '22.x'

- script: npm ci 
  displayName: 'Install Playwrite Dependencies'

- script: npx playwrite install --with-deps
  displayName: 'Install Playwrite Browsers'

- script: SECRET_KEY=demo npm run test_demo
  displayName: 'Run Tests'





